### ISSUE TITLE
Major version bumped with only a patch commit and changelog duplicated

### ISSUE THREAD

**Issue by chrisys** [product-os/flowzone#135]
See this entry for v2.0.0: https://github.com/balenaltd/handbook/blob/main/CHANGELOG.md

Related to this commit: https://github.com/balenaltd/handbook/commit/02ac2d6a5b75806f94af4987d1cf0dd75d3018ed

**Comment by klutchell** [comment]
@chrisys This is because I set the initial version of the handbook to 1.0.0 while at the same time marking the commit as major.

So when versionist ran it found no changelog and started to parse all commits to the beginning of time and found my major commit.

It retrospect my first commit should not have had a change-type and this would have been avoided.

**Comment by chrisys** [comment]
@klutchell is there a recommended way we could correct this and get back to v1.0.1?

**Comment by klutchell** [comment]
@chrisys I rewrote the history and the next PR should create the changelog and set v1.0.1

**Comment by klutchell** [comment]
This seems to be an issue with the handbook repo specifically, I will continue to investigate.

**Comment by klutchell** [comment]
Fixed by removing existing tags and adding a custom `v1.0.0` tag on master.
