### ISSUE TITLE
The change (`up sut` vs `up --exit-code-from sut`) results in the logs from the dependent services being suppressed

### ISSUE THREAD

**Issue by klutchell** [product-os/flowzone#253]
@fisehara This change (`up sut` vs `up --exit-code-from sut`) results in the logs from the dependent services being suppressed, and we only see logs from the sut service.

Was there an issue with starting all services and only using the exit code from sut?

It also goes against what was working in resinCI (not that it should matter).
https://github.com/product-os/scripts/blob/652fdd41851cda614a6a4c29cf7a14ce17bc9b6b/docker/build.sh#L238-L242

_Originally posted by @klutchell in https://github.com/product-os/flowzone/pull/197#discussion_r989359770_

**Comment by klutchell** [comment]
I just noticed this text from the [Docker docs](https://docs.docker.com/docker-hub/builds/automated-testing/)

> Only the sut service and all other services listed in [depends_on](https://docs.docker.com/compose/compose-file/compose-file-v2/#depends_on) are started. If you have services that poll for changes in other services, be sure to include the polling services in the [depends_on](https://docs.docker.com/compose/compose-file/compose-file-v2/#depends_on) list to make sure all of your services start. Also make sure to include a compose file version from 2.0 upward as depends_on was added in [version 2.0](https://docs.docker.com/compose/compose-file/compose-versioning/#version-2) file format.

So it seems like the "official" recommendation is to only start the `sut` service and it's dependencies, which is what we have now. The logs from other services can be polled manually after the tests I guess.

**Comment by fisehara** [comment]
@klutchell Sorry for redundant discussion, answered the older ping first, but here is the same answer:

Yes there was an issue on starting all services from the docker-compose file when it defines different test targets. Which is reasonable for local testing workflow to use the docker-compose.test.yml. That's why I changed it to start only the SUT.

I see that it's different to the resinCI test script, but is it necessary to have the dependent service logs in the test results, wouldn't this be too verbose?

In addition, the resinCI is using the python script based docker-compose whereas the new script uses the docker CLI compose plugin.

I'm happy to discuss and change it to a more versatile approach.

**Comment by klutchell** [comment]
I think the approach you have is good, thing only thing I've added in [this draft PR](https://github.com/product-os/flowzone/pull/249) is added some additional logging for the other services.
```
docker compose up sut --exit-code-from sut || { docker compose logs ; exit 1 ; }
docker compose logs
```
Dependent services may actually include the main backend service/server in many cases. Often I see the sut service is just a dumb client running some test command and the real meat of the logs is in the dependent services.
